export const ActionTypes = {
    IS_LOADING : 'IS_LOADING',
    FETCH_TOP_HEADLINES: 'FETCH_TOP_HEADLINES',
    FETCH_BUSINESS: 'FETCH_BUSINESS',
    FETCH_ENTERTAINMENT: 'FETCH_ENTERTAINMENT',
    FETCH_HEALTH: 'FETCH_HEALTH',
    FETCH_SCIENCE: 'FETCH_SCIENCE',
    FETCH_SPORTS: 'FETCH_SPORTS',
    FETCH_TECHNOLOGY: 'FETCH_TECHNOLOGY',
}