export const ActionTypes = {
    FETCH_IS_LOADING : 'FETCH_IS_LOADING',
    FETCH_WORLD: 'FETCH_WORLD',
    FETCH_NATION: 'FETCH_NATION',
    FETCH_TOP_HEADLINES: 'FETCH_TOP_HEADLINES',
    FETCH_BUSINESS: 'FETCH_BUSINESS',
    FETCH_ENTERTAINMENT: 'FETCH_ENTERTAINMENT',
    FETCH_HEALTH: 'FETCH_HEALTH',
    FETCH_SCIENCE: 'FETCH_SCIENCE',
    FETCH_SPORTS: 'FETCH_SPORTS',
    FETCH_TECHNOLOGY: 'FETCH_TECHNOLOGY',
    SEARCH_QUERY: 'SEARCH_QUERY',
    FETCH_SEARCH: 'FETCH_SEARCH'
}